const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
function load(file,extra={}){const source=fs.readFileSync(file,'utf8').replace(/^import .*;\r?\n/gm,'').replace(/export (async )?function/g,'$1function').replace(/export const /g,'const ');const ctx=vm.createContext({Response,NextResponse:Response,URL,console,process:{env:{}},requireAdmin:async()=>null,requireStaff:async()=>null,getSessionUser:async()=>({role:'ADMIN'}),...extra});vm.runInContext(source,ctx);return ctx;}
for(const file of ['src/app/api/menu/route.js','src/app/api/menu/[id]/route.js']){
 const method=file.includes('[id]')?'PUT':'POST';
 test(method+' menu rejects malformed/negative price before write',async()=>{let writes=0;const c=load(file,{prisma:{menuItem:{create:async()=>{writes++},update:async()=>{writes++}}}});for(const price of [-1,'-1','12abc',1.5,'1.5','',null,true,2147483648]){const r=await c[method]({json:async()=>({name:'Menu',price})},{params:{id:'1'}});assert.equal(r.status,400,String(price));}assert.equal(writes,0);});
 test(method+' menu accepts zero and integer input',async()=>{let stored;const save=async({data})=>(stored=data);const c=load(file,{prisma:{menuItem:{create:save,update:save}}});for(const price of [0,'0','12000',12000]){assert.equal((await c[method]({json:async()=>({name:'Menu',price})},{params:{id:'1'}})).status,200);assert.equal(stored.price,Number(price));}});
}
for(const [file,methods] of [['src/app/api/menu/route.js',['POST']],['src/app/api/menu/[id]/route.js',['PUT','DELETE']],['src/app/api/categories/route.js',['POST','PUT','DELETE']],['src/app/api/upload/route.js',['POST']]])test('cashier denied '+file,async()=>{const c=load(file,{requireAdmin:async()=>Response.json({error:'admin'},{status:403})});for(const m of methods)assert.equal((await c[m]({}, {params:{id:'1'}})).status,403);});
test('cashier cannot retrieve reports through alternate date parameters',async()=>{let query;const c=load('src/app/api/transaction/route.js',{getSessionUser:async()=>({role:'KASIR'}),prisma:{transaction:{findMany:async q=>{query=q;return []}}}});for(const suffix of ['', '?tab=archive&date=2026-01-01'])assert.equal((await c.GET({url:'http://localhost/api/transaction'+suffix})).status,403);assert.equal((await c.GET({url:'http://localhost/api/transaction?tab=active&date=2026-01-01'})).status,200);assert.notEqual(query.where.OR[1].createdAt.gte.toISOString().slice(0,10),'2026-01-01');});
test('recap date uses opening day across midnight',async()=>{let query;const c=load('src/app/api/transaction/route.js',{prisma:{transaction:{findMany:async q=>{query=q;return []}}}});assert.equal((await c.GET({url:'http://localhost/api/transaction?tab=archive&date=2026-09-09'})).status,200);assert.equal(query.where.createdAt.gte.toISOString(),'2026-09-08T16:00:00.000Z');assert.equal(query.where.createdAt.lte.toISOString(),'2026-09-09T15:59:59.999Z');assert.equal(query.where.completedAt,undefined);});
test('public QR omits staff/payment/kitchen identities',async()=>{const record={id:'A',createdAt:'2026-09-01T00:00:00Z',status:'completed',total:10000,paidById:99,paymentRequestId:'secret',paymentMethod:'CASH',orders:[{id:1,acceptedById:99,kitchenVersion:5,kitchenStatus:'served',items:[{id:2,quantity:1,price:10000,menuItemId:3,menuItem:{name:'Food',image:'internal',createdAt:'internal'}}]}]};const c=load('src/app/api/transaction/[id]/route.js',{getSessionUser:async()=>null,prisma:{transaction:{findUnique:async()=>record}}});const response=await c.GET({}, {params:{id:'A'}}),data=await response.json();assert.equal(response.status,200);for(const field of ['paidById','paymentRequestId','paymentMethod'])assert.equal(data[field],undefined);assert.equal(data.orders[0].acceptedById,undefined);assert.equal(data.orders[0].items[0].menuItem.name,'Food');assert.equal(data.orders[0].items[0].menuItem.image,undefined);});
test('recap separates menu IDs and historical unit prices',()=>{const page=fs.readFileSync('src/app/page.js','utf8');const start=page.indexOf('  const calculateDailyRecap ='),end=page.indexOf('  // Export Daily Recap',start);const ctx=vm.createContext({archiveTransactions:[{status:'completed',total:45000,paymentMethod:'CASH',orders:[{items:[{menuItemId:1,quantity:1,price:10000,menuItem:{name:'Same'}},{menuItemId:1,quantity:1,price:15000,menuItem:{name:'Same'}},{menuItemId:2,quantity:1,price:20000,menuItem:{name:'Same'}}]}]}]});vm.runInContext(page.slice(start,end)+'\nglobalThis.result=calculateDailyRecap()',ctx);assert.equal(ctx.result.itemList.length,3);assert.equal(ctx.result.totalRevenue,45000);for(const item of ctx.result.itemList)assert.equal(item.unitPrice*item.quantity,item.totalRevenue);});

test('cashier detail cannot bypass archive restriction with known ID',async()=>{
 const c=load('src/app/api/transaction/[id]/route.js',{getSessionUser:async()=>({role:'KASIR'}),prisma:{transaction:{findUnique:async()=>({id:'old',createdAt:'2020-01-01T00:00:00Z',status:'completed',orders:[]})}}});
 assert.equal((await c.GET({}, {params:{id:'old'}})).status,403);
});
test('admin upload fails closed without server credential',async()=>{
 const c=load('src/app/api/upload/route.js');assert.equal((await c.POST({})).status,503);
});
