const {test}=require('node:test');const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function load(path,extra={}){const s=fs.readFileSync(path,'utf8').replace(/^import .*;\r?\n/gm,'').replace(/export (async )?function/g,'$1function').replace(/export const /g,'const ');const ctx=vm.createContext({Buffer,Blob,Response,TextEncoder,NextResponse:Response,console,sharp:require('sharp'),...extra});vm.runInContext(s,ctx);return ctx;}
const policy=load('src/lib/account-policy.js');
test('account role allowlist and strong required passwords',()=>{for(const role of ['ROOT','admin','',null])assert.throws(()=>policy.accountData({name:'Test',username:'test',role,password:'Valid-Pass-123'},true));for(const password of ['',undefined,'admin123','kasir123','password123','a'.repeat(73),'abcdefghij'])assert.ok(policy.passwordError(password));for(const role of ['ADMIN','KASIR'])assert.equal(policy.accountData({name:'Test',username:' TEST ',role,password:'Valid-Pass-123'},true).role,role);});
test('account creation rejects whitespace username, invalid profile and huge password',()=>{assert.throws(()=>policy.accountData({username:'user name',name:'Test',role:'ADMIN',password:'Valid-Pass-123'},true));assert.throws(()=>policy.accountData({username:'valid',name:'',role:'ADMIN',password:'Valid-Pass-123'},true));assert.ok(policy.passwordError('🔐'.repeat(30)+'X1'));});
test('PNG validation rejects fake extension, oversized input and corrupt bytes',async()=>{const c=load('src/lib/png-upload.js');let read=false;await assert.rejects(c.normalizePng({size:6*1024*1024,arrayBuffer:async()=>{read=true;}}));assert.equal(read,false);await assert.rejects(c.normalizePng(new File(['<script>fake png</script>'],'fake.png',{type:'image/png'})));await assert.rejects(c.normalizePng(new File([Buffer.from([137,80,78,71,13,10,26,10,0])],'broken.png')));});
test('PNG is decoded and re-encoded; oversized dimensions rejected',async()=>{const c=load('src/lib/png-upload.js');const png=await require('sharp')({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer();const normalized=await c.normalizePng(new File([png],'valid.png'));assert.equal((await require('sharp')(normalized).metadata()).width,2);const huge=await require('sharp')({create:{width:4097,height:1,channels:3,background:'red'}}).png().toBuffer();await assert.rejects(c.normalizePng(new File([huge],'wide.png')));});
test('multipart reading is bounded even without a content-length header',async()=>{const c=load('src/lib/png-upload.js');const stream=new ReadableStream({start(controller){controller.enqueue(new Uint8Array(6*1024*1024));controller.close();}});await assert.rejects(c.boundedUploadForm({headers:new Headers({'content-type':'multipart/form-data; boundary=x'}),body:stream}));const form=new FormData();form.set('file',new File(['ok'],'file.png'));const req=new Request('http://localhost/api/upload',{method:'POST',body:form});assert.equal((await c.boundedUploadForm(req)).get('file').name,'file.png');});
test('kitchen disallows skipped transitions and arbitrary status',async()=>{let writes=0;const c=load('src/app/api/kitchen/[id]/route.js',{requireStaff:async()=>null,getSessionUser:async()=>({id:1}),prisma:{$transaction:async()=>{writes++;}}});for(const body of [{expectedStatus:'queued',expectedVersion:0,status:'served'},{expectedStatus:'unknown',expectedVersion:0},{expectedStatus:'__proto__',expectedVersion:0,status:'accepted'}])assert.equal((await c.PUT({json:async()=>body},{params:Promise.resolve({id:'1'})})).status,400);assert.equal(writes,0);});
test('current admin cannot delete own account or demote own role',async()=>{const c=load('src/app/api/users/[id]/route.js',{requireAdmin:async()=>null,getSessionUser:async()=>({id:1,role:'ADMIN'}),accountData:policy.accountData});assert.equal((await c.DELETE({}, {params:Promise.resolve({id:'1'})})).status,409);assert.equal((await c.PUT({json:async()=>({role:'KASIR'})},{params:Promise.resolve({id:'1'})})).status,409);});
